### PR TITLE
Added blur effect with message for marketplace and feature under deve…

### PR DESCRIPTION
**Pull request by adarshpandey18**
Added blur effect with message for marketplace and tracker screen with message "feature under development"
Screenshot from 2024-08-10 17-40-31

### CODE REVIEW

**Comment by areebahmeddd** [comment]
Hey @adarshpandey18, amazing work didn't think we could get contributors!

Could you modify the screen to have something like this?

image

-Might as well do a quick file name change -> overview_screen.dart to tracker_screen.dart

**Comment by adarshpandey18** [comment]
Sure! I would like to contribute further, but I can only do so on weekends. For the blur effect you're suggesting, I'll need to add a sample image and then apply the blur. I'll also change the file name.

**Comment by areebahmeddd** [comment]
Its alright we can contribute anytime! :)

If you need a blur image, here's what i found: https://www.freepik.com/free-vector/soft-clear-blurred-background_1111774.htm#fromView=keyword&page=1&position=1&uuid=49189764-7c31-4040-bd07-c1a2816c73b5

Thanks for your work 👊🏻

**Comment by adarshpandey18** [comment]
rather than using an blur image i will suggest using the mivro logo and then  blurring it

**Comment by areebahmeddd** [comment]
Great idea, i think @rishichirchi added in assets folder 
if not, we have one in browser extension directory (https://github.com/areebahmeddd/Mivro/blob/main/browser-extension/assets/oth-icons/logo.png)

**Comment by adarshpandey18** [comment]
image
is this good or should i change it ?

**Comment by areebahmeddd** [comment]
It's cool! go ahead, this works :)

**Comment by adarshpandey18** [comment]
Updated !

**Pull request merged**
